import React from 'react';
import Header from './Header.jsx'; // Explicitly importing with .jsx extension
import Footer from './Footer.jsx'; // Explicitly importing with .jsx extension

const About = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-gray-100 font-inter flex flex-col">
      <Header onNavigate={onNavigate} /> {/* Pass onNavigate to Header */}

      <main className="pt-24 container mx-auto p-4 flex-grow">
        <div className="bg-white p-8 rounded-lg shadow-md max-w-4xl mx-auto mb-8">
          <h2 className="text-3xl font-bold text-gray-800 mb-6 text-center">About Scan Me App</h2>
          <div className="text-gray-700 leading-relaxed space-y-4">
            <p>
              Scan Me App is a dedicated online tool designed to enhance your digital security by providing
              quick and reliable URL threat analysis. In an age where online threats like phishing, malware,
              and malicious websites are rampant, having a tool to quickly verify the safety of a link is crucial.
            </p>
            <p>
              Our application acts as a front-end interface to the powerful **VirusTotal API**. When you submit a URL
              to Scan Me App, it is securely sent to VirusTotal, which then scans it using a vast array of antivirus
              engines and website analysis tools. The comprehensive report generated by VirusTotal is then presented
              to you in an easy-to-understand format.
            </p>
            <p>
              Our mission is to empower users with the information they need to browse the internet more safely.
              We believe in providing free, accessible tools that contribute to a more secure online environment for everyone.
            </p>
            <h3 className="text-2xl font-semibold text-gray-800 mt-6 mb-3">Our Technology Stack</h3>
            <ul className="list-disc list-inside ml-4 space-y-2">
              <li>**Frontend:** Built with React.js and styled using Tailwind CSS for a responsive and modern user experience.</li>
              <li>**Backend:** Powered by FastAPI (Python), handling API requests to VirusTotal.</li>
              <li>**URL Scanning:** Integrates directly with the VirusTotal API, leveraging its extensive threat intelligence database.</li>
            </ul>
            <p className="mt-6">
              Thank you for choosing Scan Me App for your URL security needs. Stay safe online!
            </p>
          </div>
          <div className="text-center mt-8">
            <button
              onClick={() => onNavigate('home')}
              className="mt-4 bg-blue-600 text-white p-3 rounded-md font-bold hover:bg-blue-700 transition-colors duration-200 shadow-lg font-inter"
            >
              Back to Home
            </button>
          </div>
        </div>
      </main>

      <Footer onNavigate={onNavigate} /> {/* Pass onNavigate to Footer */}
    </div>
  );
};

export default About;
